name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: |
        cargo fmt --all -- --check
        for features in --no-default-features --all-features; do
          cargo clippy $features --all-targets --workspace -- -D warnings
          cargo test $features --workspace
        done
        for features in serde sha3 serde,sha3; do
          cargo clippy --no-default-features --features $features --all-targets --workspace -- -D warnings
          cargo test --no-default-features --features $features --workspace
        done
